<?php 
/**
* Implements hook_menu().
*/
function filemailer_menu() {
  $items['filemailer'] = array(
    'title' => 'File Mailer Processing Page',
    'page callback' => 'filemailer_mail_process',
    'access arguments' => array('access file mailer'),
    'type' => MENU_CALLBACK,
    'delivery callback' => 'drupal_json_output',
  );
 
  return $items;
}
/**
 * Implements hook_permission()
 */
function filemailer_permission() {
  return array(
    'access file mailer' => array(
      'title' => t('File Mailer'),
      'description' => t('Access File Mailer API.'),
    ),
  );
}
function filemailer_mail($key, &$message, $params) {
      if (isset($params['subject'])) {
        $message['subject'] = $params['subject'];
      }
      if (isset($params['body'])) {
        $message['body'][] = $params['body'];
      }
      if (isset($params['attachment'])) {
        $message['params']['attachments'][] = $params['attachment'];
      }
}
function filemailer_mail_process()
{
	if(user_is_anonymous()) {
		return false;
	}
	global $_POST;
	if($_POST['email'] && $_POST['file_fid']){
		global $user;
		$my_module = 'filemailer';
    	$my_mail_token = microtime();
		$to = $_POST['email'];
		$file_fid = $_POST['file_fid'];
		$file = file_load($file_fid);
		$filename = $file->filename;
		$filemime = $file->filemime;
		$file_uri = $file->uri;
		$file_url = file_create_url($file_uri);
		$subject = t('File Sent From ESP');
		$message = t('Please find attached file, sent to you from Pfizer Team  ');
		$message .= t(' .Thanks, ESP team.');
		$email_from = variable_get('site_mail');
		//$attachments = 	file_get_contents($file_url);
		
		$subject = "File Sent To You From ESP Team"; //Email Subject
		$headers = "From: $email_from\r\nReply-To: $email_from";
        $htmlbody = "File Sent From ESP . Please find attached file, sent to you from Pfizer Team  .Thanks, ESP team.";
		$random_hash = md5(date('r', time()));
		$headers .= "\r\nContent-Type: multipart/mixed; boundary=\"PHP-mixed-".$random_hash."\"";
		$attachment = chunk_split(base64_encode(file_get_contents($file_url))); // Set your file path here
		//define the body of the message.
		$message = "--PHP-mixed-$random_hash\r\n"."Content-Type: multipart/alternative; boundary=\"PHP-alt-$random_hash\"\r\n\r\n";
		$message .= "--PHP-alt-$random_hash\r\n"."Content-Type: text/plain; charset=\"iso-8859-1\"\r\n"."Content-Transfer-Encoding: 7bit\r\n\r\n";
		//Insert the html message.
		$message .= $htmlbody;
		$message .="\r\n\r\n--PHP-alt-$random_hash--\r\n\r\n";
		//include attachment
		$message .= "--PHP-mixed-$random_hash\r\n"."Content-Type: application/zip; name=\"$filename\"\r\n"."Content-Transfer-Encoding: base64\r\n"."Content-Disposition: attachment\r\n\r\n";
		$message .= $attachment;
		$message .= "/r/n--PHP-mixed-$random_hash--";
		//send the email
		$mail = mail( $to, $subject , $message, $headers );
		if($mail){
			return true;
		}else{
			return true;
		}	
	}else{
		return false;
	}
	 
	// //build an array called $params to pass 
	// //whatever you want to the email
	// $params['var'] = $whatevs;
	// $params['more'] = $secrets;
	 
	 
	// $sent = drupal_mail('filemailer', 'my_key', $to, language_default(), $params, $email_from, TRUE);
	 
	// if(!$sent){
	// //handle send fail, $sent ===false when mail fails, but it won't always recognize a failure
	// }
	
}
